name: appName # replace me
namespace:
  create: false
  name: default # namespace name - replace me
image:
  name: "nginx | replace me" # image name ex: docker/image:latest
docker:
  secretName: "registry-secret" 
  dockerfile:
    path: ./ # docker file location
    name: Dockerfile # dockerfile name
  debug:
    enabled: false # set to true to activate debug mode
git:
  token: PAT | replace me # Github PAT
  repository:
    name: node/node | replace me # github repository name
    branch: main # the branch you want to build
docker_registry:
  docker_config_json:
    namespace: docker.io/anybody | replace me
    username: username | replace me
    password: password | replace me
resources:
  requests:
    memory: "1024Mi"
    cpu: "150m"
  limits:
    memory: "2048Mi"
    cpu: "200m"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: instance
              operator: In
              values:
                - build
