name: app name | replace me
namespace:
  name: default | replace me # namespace name
image:
  name: "nginx | replace me" # image name ex: docker/image:latest
docker:
  dockerfile:
    path: ./ # docker file location
    name: Dockerfile # dockerfile name
  debug: 
    enabled: false # set to true to activate debug mode
git:
  token: PAT | replace me # Github PAT
  repository:
    name: node/node | replace me # github repository name
    branch: main # the branch you want to build
docker_registry:
  docker_config_json:
    namespace: docker.io/anybody | replace me
    username: username | replace me
    password: password | replace me
