apiVersion: v1
kind: Pod
metadata:
  name: {{ printf "kaniko-%s-%s" .Values.name uuidv4 }}
  namespace: {{ printf "%s-%s" .Values.namespace.name .Values.name }}
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: kaniko-{{ .Values.name}}
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile={{ printf "%s/%s" .Values.docker.dockerfile.path .Values.docker.dockerfile.name }}",
            "--context={{ printf "git://%s@github.com/%s.git#refs/heads/%s" .Values.git.token .Values.git.repository.name .Values.git.repository.branch }}",
            "--destination={{ .Values.image.name }}",
            {{- if .Values.docker.context }}
            "--context-sub-path={{ .Values.docker.context }}",
            {{- end }}
            {{- range $key, $value := .Values.docker.buildArgs }} 
            "--build-arg={{ $value }}",
            {{- end }}
            {{- if .Values.docker.debug.enabled }}
            "--verbosity=debug",
            {{- end }}
            ]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    env: {{ range $key, $value := .Values.docker.env }}
      - name: {{ $key }}
        value: {{ $value }}
    {{ end }}
    resources:
     requests:
       memory: "2048Mi"
       cpu: "250m"
     limits:
       memory: "3072Mi"
       cpu: "500m"
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: {{ .Values.docker.secretName }}
        items:
          - key: .dockerconfigjson
            path: config.json
