apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.docker.secretName }}
  namespace:  {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ tpl (.Files.Get "docker_configuration.txt" ) . | b64enc | quote }}