apiVersion: v1
kind: Secret
metadata:
  name: registry_secret
  namespace:  {{ required .Values.namespace.name  }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ tpl .Files.Get "docker_configuration.json" . | b64enc }}