apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.docker.secretName }}
  namespace:  {{ printf "%s-%s" .Values.namespace.name .Values.name }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ tpl (.Files.Get "docker_configuration.txt" ) . | b64enc | quote }}