apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace:  {{ .Values.namespace.name  }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ tpl (.Files.Get "docker_configuration.txt") . | b64enc }}