apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [{{ .Values.cmd }}]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.probes.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.probes.startupProbe | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.adminPassword }}
            - name: KC_PROXY
              value: {{ .Values.proxy }}
            - name: KC_FEATURES
              value: {{ .Values.features }}
            {{- if .Values.dbActivated }}
            - name: KC_DB
              value: {{ .Values.db }}
            - name: KC_DB_URL
              value: {{ .Values.dbUrl }}
            - name: KC_DB_USERNAME
              value: {{ .Values.dbUsername }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.dbPassword }}
            {{- end }}
            {{- if .Values.hosting.enabled }}
            - name: KC_HOSTNAME
              value: {{ .Values.hosting.hostname }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
